version = 0.1
[default.deploy.parameters]
stack_name = "rl-lambda-2025"
resolve_s3 = true
s3_prefix = "rl-lambda-2025"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
