AWSTemplateFormatVersion: '2010-09-09'

Resources:
  RecursiveLearningApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: RecursiveLearningApi
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - https://recursivelearning.app
          - https://app.recursivelearning.app
          - https://admin.recursivelearning.app
          - https://api.recursivelearning.app
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        MaxAge: 300

  RecursiveLearningApiDefaultStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref RecursiveLearningApi
      StageName: $default

  ChatRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref RecursiveLearningApi
      RouteKey: POST /chat
      Target: !Join 
        - /
        - - integrations
          - !Ref ChatIntegration

  ChatIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref RecursiveLearningApi
      Description: Lambda integration for chat endpoint
      IntegrationType: AWS_PROXY
      IntegrationUri: arn:aws:lambda:us-east-2:559050208320:function:rl-lambda-2025
      PayloadFormatVersion: 2.0

  rllambda2025ChatAPIPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: rl-lambda-2025
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RecursiveLearningApi}/*/*

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${RecursiveLearningApi}.execute-api.${AWS::Region}.amazonaws.com/
  LambdaArn:
    Description: Lambda Function ARN
    Value: arn:aws:lambda:us-east-2:559050208320:function:rl-lambda-2025 