AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  RecursiveLearningFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rl-lambda-new
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - arm64
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          REGION: us-east-2
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: integraled/central/*
      Events:
        ChatAPI:
          Type: HttpApi
          Properties:
            Path: /chat
            Method: POST
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              AllowOrigin: "'*'"
              MaxAge: "'300'"

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/chat" 