AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
      MaxAge: "'300'"

Resources:
  RecursiveLearningFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rl-lambda-2025
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - arm64
      MemorySize: 256
      Timeout: 180
      Environment:
        Variables:
          REGION: us-east-2
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/integraled/central/*'
      Events:
        ChatAPI:
          Type: HttpApi
          Properties:
            Path: /chat
            Method: POST
            Auth:
              Authorizer: NONE
            ApiId:
              Ref: RecursiveLearningApi

  RecursiveLearningApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
        AllowOrigins:
          - '*'
        MaxAge: 300

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${RecursiveLearningApi}.execute-api.${AWS::Region}.amazonaws.com/chat" 