AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.

Resources:
  rllambda2025:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rl-lambda-2025
      CodeUri: .
      Description: ''
      MemorySize: 256
      Timeout: 180
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - arm64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Environment:
        Variables:
          REGION: us-east-2
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:us-east-2:559050208320:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - arn:aws:logs:us-east-2:559050208320:log-group:/aws/lambda/rl-lambda-2025:*
        - SSMParameterReadPolicy:
            ParameterName: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/integraled/central/*'
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      Events:
        ChatAPI:
          Type: HttpApi
          Properties:
            Path: /chat
            Method: POST
            ApiId:
              Ref: RecursiveLearningApi

  RecursiveLearningApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
        AllowOrigins:
          - https://recursivelearning.app
          - https://*.recursivelearning.app
        MaxAge: 300
      UsagePlan:
        CreateUsagePlan: PER_API
        Description: Usage plan for Recursive Learning API
        Quota:
          Limit: 10000
          Period: MONTH
        Throttle:
          BurstLimit: 100
          RateLimit: 50

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${RecursiveLearningApi}.execute-api.${AWS::Region}.amazonaws.com/chat" 