AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.

Resources:
  RecursiveLearningApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: RecursiveLearningApi
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - https://recursivelearning.app
          - https://*.recursivelearning.app
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        MaxAge: 300

  RecursiveLearningApiDefaultStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref RecursiveLearningApi
      StageName: $default

  rllambda2025ChatAPIPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: rl-lambda-2025
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RecursiveLearningApi}/*/*

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${RecursiveLearningApi}.execute-api.${AWS::Region}.amazonaws.com/
  LambdaArn:
    Description: Lambda Function ARN
    Value: arn:aws:lambda:us-east-2:559050208320:function:rl-lambda-2025 